import json
import os
from pathlib import Path

# Paths
BASE_DIR = Path(__file__).resolve().parents[2]
DATA_FILE = BASE_DIR / "src" / "data" / "products.json"
OUTPUT_FILE = BASE_DIR / "src" / "frontend" / "data" / "landing-generated.ts"


def main():
    if not DATA_FILE.exists():
        print(f"❌ Error: Database not found at {DATA_FILE}")
        return

    with open(DATA_FILE, "r") as f:
        products = json.load(f)

    print(f"📥 Loaded {len(products)} products from database.")

    # Transform to Frontend Format
    vehicles = []
    for p in products:
        # Simple mapping logic - adjust fields based on your actual schema
        pricing = p.get("pricing") or []
        if pricing and isinstance(pricing, list):
            first_tier = pricing[0] or {}
            price = first_tier.get("price_aed", 0)
        else:
            price = 0
        inclusions = p.get("inclusions") or []
        specs = inclusions[:3] if isinstance(inclusions, list) else []  # Take first 3 inclusions as specs

        vehicle = {
            "id": p.get("product_id", "unknown"),
            "name": p.get("product_name", "Unnamed Product"),
            "type": p.get("category", "Adventure"),  # Fallback category
            "power": "High Performance",  # Static value for now
            "price": price,
            "image": "/assets/placeholders/buggy-generic.svg",  # Default placeholder
            "specs": specs,
        }
        vehicles.append(vehicle)

    # Generate TypeScript Content
    ts_content = f"""// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/cli/export_frontend.py

export const VEHICLES = {json.dumps(vehicles, indent=2)};
"""

    with open(OUTPUT_FILE, "w") as f:
        f.write(ts_content)

    print(f"✅ Generated frontend artifact: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
