// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/cli/export_frontend.py

export const VEHICLES = [
  {
    "id": "RaynaTours_BalloonFlights",
    "name": "Hot Air Balloon Flight",
    "type": "Adventure",
    "power": "High Performance",
    "price": 1000.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Hotel pick-up/drop-off",
      "Tea/Coffee",
      "1-hour flight"
    ]
  },
  {
    "id": "Dubai_MuseumOfTheFuture",
    "name": "Museum of the Future \u2013 General Admission",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 149.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Timed-entry admission",
      "Access to all standard exhibits and immersive zones"
    ]
  },
  {
    "id": "Dubai_DubaiFrame",
    "name": "Dubai Frame \u2013 General Admission",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 55.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Entry to Dubai Frame",
      "Access to sky bridge and galleries"
    ]
  },
  {
    "id": "Dubai_GreenPlanet",
    "name": "The Green Planet \u2013 Bio-Dome Entry",
    "type": "Family",
    "power": "High Performance",
    "price": 140.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Entry to The Green Planet bio-dome",
      "Access to all standard viewing levels"
    ]
  },
  {
    "id": "Dubai_SkyViewsObservatory",
    "name": "Sky Views Observatory \u2013 Glass Slide & Edge Walk",
    "type": "Adventure",
    "power": "High Performance",
    "price": 85.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Access to Sky Views Observatory deck",
      "One glass slide ride (per ticket)"
    ]
  },
  {
    "id": "Dubai_AinDubai",
    "name": "Ain Dubai \u2013 Observation Wheel Experience",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 130.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "One standard rotation on Ain Dubai",
      "Shared air-conditioned cabin"
    ]
  },
  {
    "id": "AbuDhabi_EtihadTowerObservationDeck",
    "name": "Etihad Tower Observation Deck at 300",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 95.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Observation deck entry"
    ]
  },
  {
    "id": "AbuDhabi_QasrAlWatan",
    "name": "Qasr Al Watan \u2013 Presidential Palace Tour",
    "type": "Cultural",
    "power": "High Performance",
    "price": 65.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Palace and garden access",
      "Entry to exhibitions and great hall"
    ]
  },
  {
    "id": "AbuDhabi_Louvre",
    "name": "Louvre Abu Dhabi \u2013 General Admission",
    "type": "Cultural",
    "power": "High Performance",
    "price": 63.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "General admission to Louvre Abu Dhabi",
      "Access to permanent galleries and main dome plaza"
    ]
  },
  {
    "id": "AbuDhabi_SheikhZayedMosqueGuided",
    "name": "Sheikh Zayed Grand Mosque \u2013 Guided Visit",
    "type": "Cultural",
    "power": "High Performance",
    "price": 50.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Mosque entry",
      "Live guide commentary"
    ]
  },
  {
    "id": "Dubai_EtihadMuseum",
    "name": "Etihad Museum \u2013 General Entry",
    "type": "Cultural",
    "power": "High Performance",
    "price": 25.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Museum admission",
      "Access to all permanent exhibits"
    ]
  },
  {
    "id": "Dubai_AlFahidiDubaiMuseum",
    "name": "Al Fahidi Historical District & Dubai Museum Visit",
    "type": "Cultural",
    "power": "High Performance",
    "price": 10.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Entry to the heritage museum/exhibit",
      "Access to Al Fahidi historical walking area"
    ]
  },
  {
    "id": "RaynaTours_QuadBikeExperience_2023",
    "name": "Quad Bike Desert Experience",
    "type": "Adventure",
    "power": "High Performance",
    "price": 150.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Safety briefing and instructions",
      "Helmet and basic protective gear",
      "Supervised quad biking in a designated desert zone"
    ]
  },
  {
    "id": "RaynaTours_DuneBuggyAdventure_2023",
    "name": "Dune Buggy Desert Adventure",
    "type": "Adventure",
    "power": "High Performance",
    "price": 350.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Helmet and safety instructions",
      "Supervised buggy driving session",
      "Choice of buggy engine (800cc or 1000cc)"
    ]
  },
  {
    "id": "RaynaTours_CamelRideLong_2023",
    "name": "Extended Camel Ride",
    "type": "Adventure",
    "power": "High Performance",
    "price": 10.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Camel ride for approximately 10 minutes",
      "Handler supervision and assistance"
    ]
  },
  {
    "id": "RaynaTours_HorseRide_2023",
    "name": "Horse Riding Experience",
    "type": "Adventure",
    "power": "High Performance",
    "price": 20.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Supervised horse ride",
      "Assistance from handlers"
    ]
  },
  {
    "id": "RaynaTours_VIPMajlisSharing_2023",
    "name": "VIP Majlis \u2013 Sharing",
    "type": "Luxury",
    "power": "High Performance",
    "price": 30.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Access to VIP seating area",
      "Premium seating set-up"
    ]
  },
  {
    "id": "RaynaTours_VIPMajlisPrivate_2023",
    "name": "VIP Majlis \u2013 Private",
    "type": "Luxury",
    "power": "High Performance",
    "price": 150.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Private Majlis seating area",
      "Premium cushions and d\u00e9cor"
    ]
  },
  {
    "id": "RaynaTours_ShishaAtTable_2023",
    "name": "Shisha at Table \u2013 Premium Upgrade",
    "type": "Culinary",
    "power": "High Performance",
    "price": 50.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Premium flavored shisha served at table"
    ]
  },
  {
    "id": "RaynaTours_AlcoholCoupons_2023",
    "name": "Alcohol Coupons",
    "type": "Culinary",
    "power": "High Performance",
    "price": 40.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "One alcoholic beverage coupon"
    ]
  },
  {
    "id": "RaynaTours_PremiumFoodUpgrade_2023",
    "name": "Premium Dining Upgrade",
    "type": "Culinary",
    "power": "High Performance",
    "price": 30.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Premium dinner menu",
      "Enhanced BBQ selection",
      "Live grill items"
    ]
  },
  {
    "id": "RaynaTours_FalconPhoto_2023",
    "name": "Falcon Photo Experience",
    "type": "Cultural",
    "power": "High Performance",
    "price": 10.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Falcon handling assistance",
      "Photo opportunity with falcon"
    ]
  },
  {
    "id": "RaynaTours_PhotoshootPackage_2023",
    "name": "Professional Desert Photoshoot",
    "type": "Luxury",
    "power": "High Performance",
    "price": 20.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Photographer service",
      "Multiple posed and candid shots"
    ]
  },
  {
    "id": "Atlantis_AquaventureDayPass_2023",
    "name": "Aquaventure Waterpark \u2013 Day Pass",
    "type": "Water Sports",
    "power": "High Performance",
    "price": 299.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Full-day access to Aquaventure Waterpark",
      "Unlimited use of rides and attractions",
      "Beach access"
    ]
  },
  {
    "id": "Atlantis_LostChambersAquarium_2023",
    "name": "Lost Chambers Aquarium \u2013 General Entry",
    "type": "Family",
    "power": "High Performance",
    "price": 140.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Entry to Lost Chambers Aquarium",
      "Access to multiple marine exhibits"
    ]
  },
  {
    "id": "Atlantis_AquaventureCombo_2023",
    "name": "Aquaventure + Lost Chambers Combo",
    "type": "Family",
    "power": "High Performance",
    "price": 335.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Full-day access to Aquaventure Waterpark",
      "General entry to Lost Chambers Aquarium"
    ]
  },
  {
    "id": "Atlantis_DolphinEncounterShallow_2023",
    "name": "Dolphin Encounter \u2013 Shallow Water",
    "type": "Family",
    "power": "High Performance",
    "price": 650.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Shallow water dolphin interaction",
      "Safety briefing",
      "Wetsuit and flotation vest"
    ]
  },
  {
    "id": "Atlantis_DolphinAdventureDeep_2023",
    "name": "Dolphin Adventure \u2013 Deep Water",
    "type": "Adventure",
    "power": "High Performance",
    "price": 900.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Deep-water interaction with dolphins",
      "Wetsuit and flotation gear",
      "Safety briefing"
    ]
  },
  {
    "id": "BurjKhalifa_AtTheTop_124125_2023",
    "name": "Burj Khalifa \u2013 At The Top (124/125)",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 169.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Access to Levels 124 and 125",
      "Use of observation decks and interactive exhibits"
    ]
  },
  {
    "id": "BurjKhalifa_SKY_148_2023",
    "name": "Burj Khalifa \u2013 SKY (Level 148)",
    "type": "Luxury",
    "power": "High Performance",
    "price": 399.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Fast-track entry",
      "Access to Level 148 lounge",
      "Refreshing drinks and hospitality service"
    ]
  },
  {
    "id": "BurjKhalifa_TheLounge_152to154_2023",
    "name": "Burj Khalifa \u2013 The Lounge",
    "type": "Luxury",
    "power": "High Performance",
    "price": 269.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Access to The Lounge (Levels 152\u2013154)",
      "Selected refreshments based on time of day"
    ]
  },
  {
    "id": "BurjKhalifa_SunriseBreakfast_2023",
    "name": "Burj Khalifa \u2013 Sunrise + Breakfast",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 159.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Sunrise access to Levels 124/125",
      "Light breakfast at The Caf\u00e9"
    ]
  },
  {
    "id": "YasIsland_FerrariWorld_2023",
    "name": "Ferrari World Abu Dhabi \u2013 1 Day Ticket",
    "type": "Adventure",
    "power": "High Performance",
    "price": 345.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "1-day park admission to Ferrari World Abu Dhabi",
      "Access to all standard rides and attractions"
    ]
  },
  {
    "id": "YasIsland_WarnerBrosWorld_2023",
    "name": "Warner Bros. World Abu Dhabi \u2013 1 Day Ticket",
    "type": "Family",
    "power": "High Performance",
    "price": 345.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "1-day park admission to Warner Bros. World Abu Dhabi",
      "Access to all standard rides and shows"
    ]
  },
  {
    "id": "YasIsland_YasWaterworld_2023",
    "name": "Yas Waterworld \u2013 1 Day Ticket",
    "type": "Water Sports",
    "power": "High Performance",
    "price": 295.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "1-day park admission to Yas Waterworld",
      "Access to all standard slides and pools"
    ]
  },
  {
    "id": "YasIsland_2Park1Day_2023",
    "name": "Yas Island \u2013 2 Parks in 1 Day",
    "type": "Family",
    "power": "High Performance",
    "price": 435.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Same-day admission to any two participating Yas Island parks"
    ]
  },
  {
    "id": "YasIsland_3Park2Day_2023",
    "name": "Yas Island \u2013 3 Parks in 2 Days",
    "type": "Family",
    "power": "High Performance",
    "price": 545.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Park admission to three Yas Island parks over two days"
    ]
  },
  {
    "id": "Dubai_ClassicCityTour",
    "name": "Classic Half Day Dubai City Tour",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 0.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Zabeel Palace Photo Stop",
      "Dubai Frame Photo Stop",
      "Bastakiya Visit"
    ]
  },
  {
    "id": "AbuDhabi_StandardCity",
    "name": "Abu Dhabi City Tour",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 0.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Sheikh Zayed Mosque",
      "Heritage Village",
      "Corniche Drive"
    ]
  },
  {
    "id": "Musandam_DibbaCruise",
    "name": "Escape to Musandam (Dibba Full Day Cruise)",
    "type": "Cruise",
    "power": "High Performance",
    "price": 0.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Border Pass",
      "Buffet Lunch",
      "Snorkeling"
    ]
  },
  {
    "id": "Adventure_QuadBike",
    "name": "Quad Bike Experience",
    "type": "Adventure",
    "power": "High Performance",
    "price": 350.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Adventure_DuneBuggy",
    "name": "Dune Buggy Adventure",
    "type": "Adventure",
    "power": "High Performance",
    "price": 600.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Concierge_Cake",
    "name": "Celebration Cake",
    "type": "Concierge",
    "power": "High Performance",
    "price": 300.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Concierge_Butler",
    "name": "Private Butler Service",
    "type": "Concierge",
    "power": "High Performance",
    "price": 350.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Dubai_ClassicHalfDayCityTour",
    "name": "Classic Half Day Dubai City Tour",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Hotel Pickup/Dropoff",
      "Zabeel Palace Photo Stop",
      "Bastakiya Visit"
    ]
  },
  {
    "id": "AbuDhabi_CityTour_Standard",
    "name": "Abu Dhabi City Tour (Standard)",
    "type": "Sightseeing",
    "power": "High Performance",
    "price": 0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": [
      "Sheikh Zayed Grand Mosque",
      "Heritage Village",
      "Corniche Drive"
    ]
  },
  {
    "id": "Dubai_Yacht_Marina_90Min",
    "name": "90-Min Sightseeing Yacht Tour",
    "type": "Cruise",
    "power": "High Performance",
    "price": 160.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Addon_Quad_350cc",
    "name": "Quad Bike 350CC (Single Seater)",
    "type": "Adventure",
    "power": "High Performance",
    "price": 350.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Addon_Quad_570cc",
    "name": "Quad Bike 570CC Sportsman (2 Seater)",
    "type": "Adventure",
    "power": "High Performance",
    "price": 500.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Addon_Buggy_1000cc",
    "name": "Polaris RZR 1000CC Buggy (4 Seater)",
    "type": "Adventure",
    "power": "High Performance",
    "price": 650.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Concierge_BirthdayCake",
    "name": "Celebration Cake (1KG)",
    "type": "Concierge",
    "power": "High Performance",
    "price": 300.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  },
  {
    "id": "Concierge_PrivateButler",
    "name": "Private Butler Service",
    "type": "Concierge",
    "power": "High Performance",
    "price": 350.0,
    "image": "/assets/placeholders/buggy-generic.svg",
    "specs": []
  }
];
